import type { Metadata } from "next";
import { Fugaz_One, Comfortaa } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Footer from "@/components/sections/Footer";
import Nav from "@/components/sections/Nav";
import clsx from "clsx";

const fugaz_One = Fugaz_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-fugaz",
});
const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Pokidex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx([fugaz_One.variable, comfortaa.variable, "dark"])}
    >
      <body className="font-comfortaa">
        <Provider>
          <Nav />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
